# -*- mode: ruby -*-
# vi: set ft=ruby :
nodes = [
    { :hostname   => 'master1',
      :ip         => '192.168.36.250',
      :box        => 'bento/centos-7',
      :ram        => 3072
    },
    { :hostname   => 'master2',
      :ip         => '192.168.36.251',
      :box        => 'bento/centos-7',
      :ram        => 3072
    }
]

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

$script = <<SCRIPT

if [[ $(cat /sys/class/net/enp0s8/operstate) != 'up' ]]; then
    service network restart
fi

function install_package() {

    yum clean all

    for i in 1 2 3
    do
        yum -y install $1 && break
    done
}

function install_puppet(){

    rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
    install_package puppet

}

which puppet || install_puppet

SCRIPT


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 4
    end
    nodes.each do |node|
        config.vm.define node[:hostname] do |nodeconfig|
            nodeconfig.vm.box = node[:box]
            nodeconfig.vm.hostname = node[:hostname]
            nodeconfig.vm.network :private_network, ip: node[:ip]
            if node[:mysql_port]
                nodeconfig.vm.network :forwarded_port, host: node[:mysql_port], guest: 3306
            end

            memory = node[:ram] ? node[:ram] : 256
            nodeconfig.vm.provider :virtualbox do |vb|
                vb.customize [
                                 'modifyvm', :id,
                                 '--cpuexecutioncap', '90',
                                 '--memory', memory.to_s,
                             ]

            end
        end
        config.vm.synced_folder '..', '/twindb_backup'
    end

    config.vm.provision 'shell', inline: $script
    config.vm.provision :puppet do |puppet|
        puppet.environment_path = 'environment'
        puppet.environment = 'puppet'
    end
end
