#!/bin/sh
#
# Perform necessary twindb-backup setup steps
# after package is installed.
#

PROGNAME=`basename $0`
INSTALL_DIR=/opt/twindb-backup
CONFIG_DIR=/etc/twindb
LOG_DIR=/var/log/twindb-backup
PREFIX="/usr"

DISTRIBUTION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon|SUSE)" /etc/issue 2>/dev/null || uname -s)

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

mkdir -p ${LOG_DIR} || error_exit "Cannot create ${LOG_DIR}!"

# setup config
mkdir -p ${CONFIG_DIR} || error_exit "Cannot create ${CONFIG_DIR}!"
cp $INSTALL_DIR/support/twindb-backup.cfg $CONFIG_DIR/
chmod 600 $CONFIG_DIR/twindb-backup.cfg

# setup cron
cp $INSTALL_DIR/support/twindb-backup.cron /etc/cron.d/twindb-backup

# setup links to the executables
rm -f $PREFIX/bin/twindb-backup
ln -sf $INSTALL_DIR/bin/twindb-backup $PREFIX/bin || error_exit "Cannot link twindb-backup to $PREFIX/bin"

chown -Rh 0:0 $INSTALL_DIR

echo "Thank you for installing twindb-backup!"

exit 0
