---
name: "Integration tests"

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: "boolean"
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
      pause_test:
        type: "choice"
        description: "if 1, the test will be paused upon error"
        required: false
        default: "0"
        options:
          - "0"
          - "1"
jobs:
  test:
    runs-on: "ubuntu-latest"
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      PAUSE_TEST: "${{ inputs.pause_test }}"
    strategy:
      matrix:
        version: ["focal", "bionic", "7"]
    steps:
      - uses: "actions/checkout@v3"
      - name: "Setup Python env"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.9

      - name: "Setup tmate session"
        uses: "mxschmitt/action-tmate@v3"
        if: >
          ${{
            github.event_name == 'workflow_dispatch'
            && inputs.debug_enabled
          }}

      - name: "Run tests"
        run: |
          pip install -U "pip ~= 22.0.0"
          python -m venv ~/.env
          source ~/.env/bin/activate
          make bootstrap
          python tests/integration/run_all.py --no-pause ${{ matrix.version }}

...
