name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
         
    - name: Install dependencies
      run: make bootstrap
      
    - name: Run check
      run: make lint
      
    - name: Run tests
      run: make tests
