---
name: "Makefile CI"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Setup Python env"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.9

      - name: "Run tests"
        run: |
          pip install -U "pip ~= 22.0.0"
          python -m venv ~/.env
          source ~/.env/bin/activate
          make bootstrap lint test
...
